/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Customer;

import admin.Inventory;
import classes.DataModel;
import connection.connect1;
import java.text.DecimalFormat;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


/**
 *
 * @author gardh
 */
public class WalkInPanel extends javax.swing.JPanel {

    private int Oid;
    private String Poption = "";
    private double amount = 0;
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public WalkInPanel() {
        initComponents();
        con = connect1.con();
        Oid = DataModel.getDataInt();
        
         DecimalFormat ft =  new DecimalFormat("#.00");
        
        try {
            pst = con.prepareCall("SELECT SUM(subtotal) FROM tbl_orderdetails WHERE order_id = ?");
            pst.setInt(1, Oid);
            rs = pst.executeQuery();
            while (rs.next()) {                
                amount = rs.getDouble("SUM(subtotal)");
               
                totalAmount.setText(String.valueOf(ft.format(amount)));
                
                
                try {
                    
                   pst = con.prepareCall("UPDATE tbl_orders SET total_amount = ? WHERE order_id = ?");
                   pst.setDouble(1,amount );
                   pst.setInt(2,Oid );
                   pst.executeUpdate();
                    
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        cashC = new javax.swing.JRadioButton();
        walletcbox = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        totalAmount = new javax.swing.JLabel();
        button1 = new classes.Button();
        payment_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Payment Option");

        buttonGroup1.add(cashC);
        cashC.setForeground(new java.awt.Color(0, 0, 0));
        cashC.setText("CASH");
        cashC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashCActionPerformed(evt);
            }
        });

        buttonGroup1.add(walletcbox);
        walletcbox.setForeground(new java.awt.Color(0, 0, 0));
        walletcbox.setText("E-WALLET");
        walletcbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walletcboxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Total Amount:  P");

        totalAmount.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        totalAmount.setForeground(new java.awt.Color(0, 0, 0));
        totalAmount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalAmount.setText("0.00");

        button1.setText("PAY");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        payment_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                payment_txtKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Enter Payment:  P");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(walletcbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cashC, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(payment_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(cashC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(walletcbox)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(totalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payment_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

       
       
            if (cashC.isSelected() ){
                if (!payment_txt.getText().isEmpty()) {
                 double paymnt = Double.parseDouble(payment_txt.getText());
                    double Tamount = Double.parseDouble(totalAmount.getText());
                            if (paymnt < Tamount) {
                                JOptionPane.showMessageDialog(null,"Unable to pay.");
                            }
                               if(paymnt == Tamount){
                                   insertProduct(Oid);
                                JOptionPane.showMessageDialog(null,"Payment succesfull.");
                                  CustomerDashboard cd = new CustomerDashboard();
                                  cd.setVisible(true);
                                   JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(WalkInPanel.this);
                                   topFrame.dispose();
                            }  
                              if(paymnt > Tamount) {
                                   insertProduct(Oid);
                                double change = paymnt - Tamount;
                                  JOptionPane.showMessageDialog(null,"Payment succesfull.\n Change is P" +change);
                                  CustomerDashboard cd = new CustomerDashboard();
                                  cd.setVisible(true);
                                   JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(WalkInPanel.this);
                                   topFrame.setVisible(false);
                                   
                            }
                      
                
            }else {
             JOptionPane.showMessageDialog(null,"Please enter payment amount."); }
           
            }
            else if (walletcbox.isSelected()) {
                
                 DataModel.setDatDouble(amount);
            EwalletPanel wallet = new EwalletPanel();
            wallet.setVisible(true);
            PlaceOrder p = new PlaceOrder();
            p.setVisible(false);
          
            }
            else{
                JOptionPane.showInternalMessageDialog(null, "Select payment option.");
            }
            
    }//GEN-LAST:event_button1ActionPerformed

    private void payment_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payment_txtKeyTyped
        char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();
                }
    }//GEN-LAST:event_payment_txtKeyTyped

    private void cashCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashCActionPerformed
      
        if(cashC.isSelected()){
        Poption = "CASH";
      
        }
    }//GEN-LAST:event_cashCActionPerformed

    private void walletcboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walletcboxActionPerformed
      
          if(cashC.isSelected()){
        Poption = "E-WALLET";
     
        }
    }//GEN-LAST:event_walletcboxActionPerformed


    private void insertProduct(int ID) {
     try {
                
                pst = con.prepareCall("UPDATE `tbl_orders` SET `Status`= ? WHERE order_id = ?");
                pst.setString(1, "PURCHASED");
                pst.setInt(2, ID);
                pst.executeUpdate();
                
               
                
            } catch (Exception e) {
                e.printStackTrace();
            }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private classes.Button button1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cashC;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField payment_txt;
    private javax.swing.JLabel totalAmount;
    private javax.swing.JRadioButton walletcbox;
    // End of variables declaration//GEN-END:variables
}
