/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin;

import classes.ScrollBar;
import connection.connect1;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author gardh
 */
public class ManagePayment extends javax.swing.JPanel {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    /**
     * Creates new form OrdersPanel
     */
    public ManagePayment() {
        initComponents();
        con = connect1.con();
        
        scrollpane1.setVerticalScrollBar(new ScrollBar());
        
        
        try {
            pst = con.prepareCall("SELECT tbl_payment.payment_id, tbl_customer.fullname, tbl_payment.timestamp, tbl_orders.total_amount "
                    + "FROM tbl_orders JOIN tbl_customer ON tbl_orders.customer_id = tbl_customer.customer_id "
                    + "JOIN tbl_payment on tbl_orders.order_id = tbl_payment.order_id;");
            
              rs =  pst.executeQuery();
              
              while(rs.next()){
            Object[] rowdata = new Object[4];
            
            for(int i = 0; i < 4; i++){
            
                rowdata[i] =rs.getObject(i+1);
            
            }
            table1.addRow(rowdata);
            
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new Panel.panelBorder();
        scrollpane1 = new javax.swing.JScrollPane();
        table1 = new classes.Table();
        jLabel1 = new javax.swing.JLabel();
        deleteBtn = new classes.Button();
        clearBtn = new classes.Button();

        setBackground(new java.awt.Color(242, 242, 242));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        scrollpane1.setBorder(null);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment ID", "Costumer Name", "Time", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpane1.setViewportView(table1);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PAYMENT MANAGEMENT");

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollpane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        deleteBtn.setBackground(new java.awt.Color(248, 49, 9));
        deleteBtn.setText("DELETE PAYMENT");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(249, 106, 6));
        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(231, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed

        int confirmation = JOptionPane.showConfirmDialog(
            null, "Are you sure you want to delete this order from the table?", "Confirm", JOptionPane.YES_NO_OPTION
        );

        if (confirmation == JOptionPane.YES_OPTION) {
            deleteTableData();
            loadDatafromDataBase();
          
        }

    }//GEN-LAST:event_deleteBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
         int confirmation = JOptionPane.showConfirmDialog(
        null, "Are you sure you want to clear all data from the table?", "Confirm", JOptionPane.YES_NO_OPTION
    );

                                if (confirmation == JOptionPane.YES_OPTION) {
                                    clearTableDataUser();
                                } 
                                          
        
    }//GEN-LAST:event_clearBtnActionPerformed

    
    private void deleteTableData(){

      int selectedRow = table1.getSelectedRow();

              
                    // Extract information from the selected row
                    int paymentid = (int) table1.getValueAt(selectedRow, 0);

                    String sql = "SELECT order_id FROM tbl_payment WHERE payment_id = ?";

                    try (PreparedStatement statement = con.prepareStatement(sql)) {
                    
                        statement.setInt(1, paymentid);

                            try (ResultSet resultSet = statement.executeQuery()) {
                                if (resultSet.next()) {
                                    int orderId = resultSet.getInt("order_id");
                                  
                                    try {
                                      pst = con.prepareCall("DELETE FROM tbl_orders WHERE order_id = ?");
                                      pst.setInt(1,orderId);
                                      pst.executeUpdate();
                                      
                                        DefaultTableModel model = (DefaultTableModel) table1.getModel();
                                        model.removeRow(selectedRow);
                                      
                                    } catch (Exception e) {
                                        e.printStackTrace();
                                    }
                                    
                                }
                            }
                        

                        
                       

                      
       
                    
                    } catch (SQLException ex) {
                        Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
                    }


}
    
  private void loadDatafromDataBase(){
     
         con = connect1.con();
         
         DefaultTableModel model = (DefaultTableModel) table1.getModel();
         model.setRowCount(0);
         
           try {
            pst = con.prepareCall("SELECT tbl_payment.payment_id, tbl_customer.fullname, tbl_payment.timestamp, tbl_orders.total_amount "
                    + "FROM tbl_orders JOIN tbl_customer ON tbl_orders.customer_id = tbl_customer.customer_id "
                    + "JOIN tbl_payment on tbl_orders.order_id = tbl_payment.order_id; ");
            rs = pst.executeQuery();
            
            while(rs.next()){
            Object[] rowdata = new Object[4];
            
            for(int i = 0; i <4 ; i++){
            
                rowdata[i] =rs.getObject(i+1);
            
            }
            model.addRow(rowdata);
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(DashboardPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
         
     }      
    
  private void clearTableDataUser() {
    String sql = "DELETE FROM tbl_orders";
    
    try (PreparedStatement statement = con.prepareStatement(sql)) {
        statement.executeUpdate();
        JOptionPane.showMessageDialog(null, "All data cleared from the table.");
        
        // Refresh the table after clearing data
        loadDatafromDataBase();
    } catch (SQLException ex) {
        Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
    }
}

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private classes.Button clearBtn;
    private classes.Button deleteBtn;
    private javax.swing.JLabel jLabel1;
    private Panel.panelBorder panelBorder1;
    private javax.swing.JScrollPane scrollpane1;
    private classes.Table table1;
    // End of variables declaration//GEN-END:variables
}
